// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        NButton: typeof import('naive-ui')['NButton']
        NConfigProvider: typeof import('naive-ui')['NConfigProvider']
        NDialogProvider: typeof import('naive-ui')['NDialogProvider']
        NDivider: typeof import('naive-ui')['NDivider']
        NIcon: typeof import('naive-ui')['NIcon']
        NLayout: typeof import('naive-ui')['NLayout']
        NLayoutContent: typeof import('naive-ui')['NLayoutContent']
        NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
        NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
        NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
        NMenu: typeof import('naive-ui')['NMenu']
        NMessageProvider: typeof import('naive-ui')['NMessageProvider']
        NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
        NSpace: typeof import('naive-ui')['NSpace']
        NText: typeof import('naive-ui')['NText']
        NThing: typeof import('naive-ui')['NThing']
    }
}
