// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
    export interface GlobalComponents {
        NAlert: typeof import('naive-ui')['NAlert']
        NButton: typeof import('naive-ui')['NButton']
        NCard: typeof import('naive-ui')['NCard']
        NConfigProvider: typeof import('naive-ui')['NConfigProvider']
        NDescriptions: typeof import('naive-ui')['NDescriptions']
        NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
        NDialogProvider: typeof import('naive-ui')['NDialogProvider']
        NDivider: typeof import('naive-ui')['NDivider']
        NEl: typeof import('naive-ui')['NEl']
        NForm: typeof import('naive-ui')['NForm']
        NFormItem: typeof import('naive-ui')['NFormItem']
        NGrid: typeof import('naive-ui')['NGrid']
        NGridItem: typeof import('naive-ui')['NGridItem']
        NIcon: typeof import('naive-ui')['NIcon']
        NInput: typeof import('naive-ui')['NInput']
        NLayout: typeof import('naive-ui')['NLayout']
        NLayoutContent: typeof import('naive-ui')['NLayoutContent']
        NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
        NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
        NLayoutSider: typeof import('naive-ui')['NLayoutSider']
        NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
        NMenu: typeof import('naive-ui')['NMenu']
        NMessageProvider: typeof import('naive-ui')['NMessageProvider']
        NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
        NSpace: typeof import('naive-ui')['NSpace']
        NStatistic: typeof import('naive-ui')['NStatistic']
        NTabPane: typeof import('naive-ui')['NTabPane']
        NTabs: typeof import('naive-ui')['NTabs']
        NText: typeof import('naive-ui')['NText']
        NThing: typeof import('naive-ui')['NThing']
    }
}
