<?php

namespace App\GeometryDash\Enums;

enum GeometryDashAudioTrackIds: int
{
	case PRACTICE_STAY_INSIDE_ME_BY_OCULARNEBULA = -1;
	case STEREO_MADNESS_BY_FOREVERBOUND = 0;
	case BACK_ON_TRACK_BY_DJVI = 1;
	case POLARGEIST_BY_STEP = 2;
	case DRY_OUT_BY_DJVI = 3;
	case BASE_AFTER_BASE_BY_DJVI = 4;
	case CANT_LET_GO_BY_DJVI = 5;
	case JUMPER_BY_WATERFLAME = 6;
	case TIME_MACHINE_BY_WATERFLAME = 7;
	case CYCLES_BY_DJVI = 8;
	case XSTEP_BY_DJVI = 9;
	case CLUTTERFUNK_BY_WATERFLAME = 10;
	case THEORY_OF_EVERYTHING_BY_DJ_NATE = 11;
	case ELECTROMAN_ADVENTURES_BY_WATERFLAME = 12;
	case CLUBSTEP_BY_DJ_NATE = 13;
	case ELECTRODYNAMIX_BY_DJ_NATE = 14;
	case HEXAGON_FORCE_BY_WATERFLAME = 15;
	case BLAST_PROCESSING_BY_WATERFLAME = 16;
	case THEORY_OF_EVERYTHING_2_BY_DJ_NATE = 17;
	case GEOMETRICAL_DOMINATOR_BY_WATERFLAME = 18;
	case DEADLOCKED_BY_F_777 = 19;
	case FINGERDASH_BY_MDK = 20;
	case DASH_BY_MDK = 21;
	case EXPLORERS_BY_HINKIK = 22;
	case THE_SEVEN_SEAS_BY_F_777 = 23;
	case VIKING_ARENA_BY_F_777 = 24;
	case AIRBORNE_ROBOTS_BY_F_777 = 25;
	case SECRET_BY_ROBTOP = 26;
	case PAYLOAD_BY_DEX_ARSON = 27;
	case BEAST_MODE_BY_DEX_ARSON = 28;
	case MACHINA_BY_DEX_ARSON = 29;
	case YEARS_BY_DEX_ARSON = 30;
	case FRONTLINES_BY_DEX_ARSON = 31;
	case SPACE_PIRATES_BY_WATERFLAME = 32;
	case STRIKER_BY_WATERFLAME = 33;
	case EMBERS_BY_DEX_ARSON = 34;
	case ROUND_1_BY_DEX_ARSON = 35;
	case MONSTER_DANCE_OFF_BY_F_777 = 36;
	case PRESS_START_BY_MDK = 37;
	case NOCK_EM_BY_BOSSFIGHT = 38;
	case POWER_TRIP_BY_BOOM_KITTY = 39;
}