<?php

namespace App\Enums;

use App\Services\Game\AlgorithmService;

enum Response: int
{
    case SUCCESS = 1;
    case FAILED = -1;
    case SPECIAL_FAILED = -2;

    case ACCOUNT_REGISTER_EMAIL_ALREADY_IN_USE = -3;
    case ACCOUNT_REGISTER_USER_NAME_INVALID = -4;
    case ACCOUNT_REGISTER_PASSWORD_INVALID = -5;
    case ACCOUNT_REGISTER_EMAIL_INVALID = -6;
    case ACCOUNT_REGISTER_PASSWORD_TOO_SHORT = -8;
    case ACCOUNT_REGISTER_USER_NAME_TOO_SHORT = -9;
    case ACCOUNT_LOGIN_FAILED = -11;

    case COMMENT_CREATE_FAILED_BANNED = -10;
    case ACCOUNT_LOGIN_FAILED_BANNED = -12;

    public const INVALID_RESPONSE = Response::FAILED;

    public const REQUEST_VALIDATION_FAILED = Response::FAILED;

    public const REQUEST_AUTHORIZATION_FAILED = Response::FAILED;

    public const ACCOUNT_REGISTER_SUCCESS = Response::SUCCESS;

    public const ACCOUNT_REGISTER_USER_NAME_ALREADY_IN_USE = Response::SPECIAL_FAILED;

    public const ACCOUNT_LOGIN_FAILED_EMAIL_NOT_VERIFIED = Response::FAILED;

    public const ACCOUNT_SETTING_UPDATE_SUCCESS = Response::SUCCESS;

    public const ACCOUNT_COMMENT_DELETE_SUCCESS = Response::SUCCESS;

    public const ACCOUNT_COMMENT_DELETE_FAILED = Response::FAILED;

    public const ACCOUNT_DATA_SAVE_SUCCESS = Response::SUCCESS;

    public const ACCOUNT_DATA_LOAD_FAILED = Response::FAILED;

    public const MOD_ACCESS_NOT_FOUND = Response::FAILED;

    public const USER_FETCH_EMPTY_RESULT = Response::SPECIAL_FAILED;

    public const LEADERBOARD_FETCH_FAILED_TYPE_NOT_FOUND = Response::FAILED;

    public const MESSAGE_UPDATE_FAILED_TARGET_NOT_FOUND = Response::FAILED;

    public const MESSAGE_UPDATE_FAILED_TARGET_BLOCKED = Response::FAILED;

    public const MESSAGE_FETCH_FAILED_EMPTY = Response::SPECIAL_FAILED;

    public const MESSAGE_DOWNLOAD_FAILED_MESSAGE_NOT_FOUND = Response::FAILED;

    public const MESSAGE_DELETE_SUCCESS = Response::SUCCESS;

    public const MESSAGE_DELETE_FAILED_MESSAGE_NOT_FOUND = Response::FAILED;

    public const LEVEL_SEARCH_FAILED_NOT_SUPPORT_TYPE = Response::FAILED;

    public const LEADERBOARD_FETCH_FAILED_ACCOUNT_VALIDATE_FAILED = Response::FAILED;

    public const LEVEL_SEARCH_FAILED_AUTH_FAILED = Response::FAILED;

    public const LEVEL_DOWNLOAD_FAILED_DATA_MISSING = Response::FAILED;

    public const LEVEL_DELETE_SUCCESS = Response::SUCCESS;

    public const LEVEL_DELETE_FAILED_NO_PERMISSION = Response::FAILED;

    public const LEVEL_DESC_UPDATE_SUCCESS = Response::SUCCESS;

    public const LEVEL_DESC_UPDATE_FAILED_NO_PERMISSION = Response::FAILED;

    public const LEVEL_COMMENTS_FETCH_FAILED_INVALID_MODE = Response::FAILED;

    public const LEVEL_COMMENT_DELETE_SUCCESS = Response::SUCCESS;

    public const LEVEL_COMMENT_DELETE_FAILED = Response::FAILED;

    public const LEVEL_COMMENTS_EMPTY = Response::SPECIAL_FAILED;

    public const ACCOUNT_FRIEND_REQUEST_DELETE_SUCCESS = Response::SUCCESS;

    public const ACCOUNT_FRIEND_REQUEST_DELETE_FAILED = Response::FAILED;

    public const ACCOUNT_FRIEND_REQUEST_EMPTY = Response::SPECIAL_FAILED;

    public const ACCOUNT_BLOCK_FAILED = Response::FAILED;

    public const ACCOUNT_BLOCK_SUCCESS = Response::SUCCESS;

    public const ACCOUNT_UNBLOCK_SUCCESS = Response::SUCCESS;

    public const ACCOUNT_UNBLOCK_FAILED = Response::FAILED;

    public const USER_FETCH_FAILED_INVALID_TYPE = Response::FAILED;

    public const ACCOUNT_INFO_FETCH_FAILED_BLOCKED = Response::FAILED;

    public const ACCOUNT_FRIEND_REQUEST_SEND_FAILED_TARGET_BLOCKED = Response::FAILED;

    public const ACCOUNT_FRIEND_REMOVE_SUCCESS = Response::SUCCESS;

    public const ACCOUNT_FRIEND_REMOVE_FAILED = Response::FAILED;

    public const ACCOUNT_FRIEND_REQUEST_ACCEPT_SUCCESS = Response::SUCCESS;

    public const ACCOUNT_FRIEND_REQUEST_ACCEPT_FAILED = Response::FAILED;

    public const ACCOUNT_COMMENT_HISTORY_EMPTY = Response::SPECIAL_FAILED;

    public const ACCOUNT_COMMENT_HISTORY_FETCH_FAILED_INVALID_MODE = Response::FAILED;

    public const DAILY_OR_WEEKLY_LEVEL_FETCH_FAILED_NOT_FOUND = Response::FAILED;

    public const LEVEL_DOWNLOAD_FAILED_NO_LEVEL = Response::FAILED;

    public const LIKE_FAILED_INVALID_TYPE = Response::FAILED;

    public const LIKE_SUCCESS = Response::SUCCESS;

    public const LEVEL_SCORE_FETCH_FAILED_INVALID_TYPE = Response::FAILED;

    public const LEVEL_RATE_FAILED_USER_ALREADY_RATED = Response::FAILED;

    public const LEVEL_RATE_SUGGESTION_SUBMITTED = Response::SUCCESS;

    public const LEVEL_RATE_FAILED_ALREADY_RATED = Response::FAILED;

    public const LEVEL_RATE_SUCCESS = Response::SUCCESS;

    public const LEVEL_RATE_DEMON_FAILED_NOT_RATED = Response::FAILED;

    public const LEVEL_RATE_FAILED_UNKNOWN_ERROR = Response::FAILED;

    public const LEVEL_RATE_DEMON_SUCCESS = Response::SUCCESS;

    public const LEVEL_RATE_DEMON_SUGGESTION_SUBMITTED = Response::SUCCESS;

    public const LEVEL_RATE_DEMON_FAILED_USER_ALREADY_RATED = Response::FAILED;

    public const LEVEL_RATE_DEMON_FAILED_UNKNOWN_ERROR = Response::FAILED;

    public const LEVEL_RATE_DEMON_FAILED_NO_PERMISSION = Response::SPECIAL_FAILED;

    public const LEVEL_RATE_SUGGEST_FAILED_ALREADY_SUGGESTED = Response::FAILED;

    public const ITEM_RESTORE_FAILED = Response::FAILED;

    public const LIKE_FAILED = Response::FAILED;

    public const SONG_NOT_FOUND = Response::FAILED;

    public const ACCOUNT_COMMENT_CREATE_FAILED = Response::FAILED;

    public const SONG_DISABLED = Response::SPECIAL_FAILED;

    public const SONG_FETCH_FAILED = Response::FAILED;

    public const PROXY_FAILED = Response::FAILED;

    public static function empty(): string
    {
        return '#' . AlgorithmService::genPage(1, 0);
    }

    public const GAME_SPECIAL_FAILED_2 = Response::SPECIAL_FAILED;
    public const GAME_SPECIAL_FAILED_12 = Response::ACCOUNT_LOGIN_FAILED_BANNED;
    public const GAME_REQUEST_AUTHORIZATION_FAILED = Response::FAILED;
    public const GAME_REQUEST_VALIDATE_FAILED = Response::FAILED;
    public const GAME_ACCOUNT_BLOCK_SUCCESS = Response::SUCCESS;
    public const GAME_ACCOUNT_BLOCK_FAILED_ALREADY_EXISTS = Response::FAILED;
    public const GAME_ACCOUNT_UNBLOCK_SUCCESS = Response::SUCCESS;
    public const GAME_ACCOUNT_UNBLOCK_FAILED_NOT_FOUND = Response::FAILED;
    public const GAME_ACCOUNT_COMMENT_INDEX_FAILED_TARGET_NOT_FOUND = Response::FAILED;
    public const GAME_ACCOUNT_COMMENT_DELETE_SUCCESS = Response::SUCCESS;
    public const GAME_ACCOUNT_COMMENT_DELETE_FAILED_NOT_FOUND = Response::FAILED;
    public const GAME_ACCOUNT_COMMENT_DELETE_FAILED_NOT_OWNER = Response::FAILED;
    public const GAME_ACCOUNT_COMMENT_HISTORY_INDEX_FAILED_EMPTY = Response::GAME_SPECIAL_FAILED_2;
    public const GAME_ACCOUNT_COMMENT_HISTORY_INDEX_FAILED_INVALID_MODE = Response::FAILED;
    public const GAME_ACCOUNT_REGISTER_SUCCESS = Response::SUCCESS;
    public const GAME_ACCOUNT_PROFILE_FETCH_FAILED_TARGET_NOT_FOUND = Response::FAILED;
    public const GAME_ACCOUNT_PROFILE_FETCH_FAILED_BLOCKED_BY_TARGET = Response::FAILED;
    public const GAME_ACCOUNT_ACCESS_REQUEST_FAILED_NOT_FOUND = Response::FAILED;
    public const GAME_ACCOUNT_LOGIN_FAILED_NEED_VERIFY_EMAIL = Response::FAILED;
    public const GAME_ACCOUNT_LOGIN_FAILED_BANNED = Response::GAME_SPECIAL_FAILED_12;
    public const GAME_ACCOUNT_DATA_SAVE_SUCCESS = Response::SUCCESS;
    public const GAME_ACCOUNT_DATA_LOAD_FAILED_NOT_FOUND = Response::FAILED;
    public const GAME_ACCOUNT_FRIEND_DELETE_SUCCESS = Response::SUCCESS;
    public const GAME_ACCOUNT_FRIEND_DELETE_FAILED_TARGET_NOT_FRIEND = Response::FAILED;
    public const GAME_ACCOUNT_FRIEND_REQUEST_CREATE_FAILED_TARGET_NOT_FOUND = Response::FAILED;
    public const GAME_ACCOUNT_FRIEND_REQUEST_CREATE_FAILED_BLOCKED_BY_TARGET = Response::FAILED;
    public const GAME_ACCOUNT_FRIEND_REQUEST_CREATE_FAILED_TARGET_DISABLED = Response::FAILED;
    public const GAME_ACCOUNT_FRIEND_REQUEST_INDEX_FAILED_EMPTY = Response::GAME_SPECIAL_FAILED_2;
    public const GAME_ACCOUNT_FRIEND_REQUEST_ACCEPT_FAILED_NOT_FOUND = Response::FAILED;
    public const GAME_ACCOUNT_FRIEND_REQUEST_ACCEPT_FAILED_TARGET_ACCOUNT_NOT_MATCH = Response::FAILED;
    public const GAME_ACCOUNT_FRIEND_REQUEST_ACCEPT_FAILED_NOT_RECEIVER = Response::FAILED;
    public const GAME_ACCOUNT_FRIEND_REQUEST_ACCEPT_SUCCESS = Response::SUCCESS;
    public const GAME_ACCOUNT_FRIEND_REQUEST_DELETE_FAILED_NOT_FOUND = Response::FAILED;
    public const GAME_ACCOUNT_FRIEND_REQUEST_DELETE_SUCCESS = Response::SUCCESS;
    public const GAME_ACCOUNT_MESSAGE_CREATE_FAILED_TARGET_NOT_FOUND = Response::FAILED;
    public const GAME_ACCOUNT_MESSAGE_CREATE_FAILED_BLOCKED_BY_TARGET = Response::FAILED;
    public const GAME_ACCOUNT_MESSAGE_CREATE_FAILED_TARGET_DISABLED = Response::FAILED;
    public const GAME_ACCOUNT_MESSAGE_CREATE_FAILED_TARGET_DISABLED_FRIENDS_ONLY = Response::FAILED;
    public const GAME_ACCOUNT_MESSAGE_INDEX_FAILED_EMPTY = Response::GAME_SPECIAL_FAILED_2;
    public const GAME_ACCOUNT_MESSAGE_FETCH_FAILED_NOT_FOUND = Response::FAILED;
    public const GAME_ACCOUNT_MESSAGE_FETCH_FAILED_NOT_OWNER = Response::FAILED;
    public const GAME_ACCOUNT_MESSAGE_DELETE_FAILED_NOT_FOUND = Response::FAILED;
    public const GAME_ACCOUNT_MESSAGE_DELETE_SUCCESS = Response::SUCCESS;
    public const GAME_ACCOUNT_SETTING_UPDATE_SUCCESS = Response::SUCCESS;
    public const GAME_CHALLENGE_GENERATE_FAILED_UNEXPECTED_EXCEPTION = Response::SUCCESS;
    public const GAME_SONG_FETCH_FAILED_NOT_FOUND = Response::FAILED;
    public const GAME_SONG_FETCH_FAILED_NOT_FOUND_CUSTOM = Response::FAILED;
    public const GAME_SONG_FETCH_FAILED_PROCESS_EXCEPTION = Response::FAILED;
    public const GAME_SONG_FETCH_FAILED_DISABLED = Response::FAILED;
    public const GAME_USER_INDEX_FAILED_INVALID_MODE = Response::FAILED;
    public const GAME_USER_INDEX_FAILED_EMPTY = Response::GAME_SPECIAL_FAILED_2;
    public const GAME_USER_SEARCH_FAILED_EMPTY = Response::GAME_SPECIAL_FAILED_2;
    public const GAME_ITEM_RESTORE_SUCCESS = Response::SUCCESS;
    public const GAME_ITEM_LIKE_SUCCESS = Response::SUCCESS;
    public const GAME_ITEM_LIKE_FAILED_INVALID_TYPE = Response::FAILED;
    public const GAME_ITEM_LIKE_FAILED_ALREADY_EXISTS = Response::FAILED;
    public const GAME_LEVEL_COMMENT_INDEX_FAILED_LEVEL_NOT_FOUND = Response::FAILED;
    public const GAME_LEVEL_COMMENT_INDEX_FAILED_EMPTY = Response::GAME_SPECIAL_FAILED_2;
    public const GAME_LEVEL_COMMENT_INDEX_FAILED_INVALID_MODE = Response::FAILED;
    public const GAME_LEVEL_COMMENT_DELETE_FAILED_NOT_FOUND = Response::FAILED;
    public const GAME_LEVEL_COMMENT_DELETE_FAILED_PARAMETER_VALIDATE_FAILED = Response::FAILED;
    public const GAME_LEVEL_COMMENT_DELETE_FAILED_NOT_OWNER = Response::FAILED;
    public const GAME_LEVEL_COMMENT_DELETE_SUCCESS = Response::SUCCESS;
}
